version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run build
            - run: mkdir -p /tmp/core_dumps
            - run: cp -rf build /tmp/core_dumps
            - run: npm test
            - store_artifacts: path: /tmp/core_dumps
workflows:
    build-and-test:
      jobs:
        - build-and-test
